# Key 亂放公開 Github 上會悲劇，確定這是 Trial Key

production:
  cloud_name: "kerjadulu-staging"
  api_key: "851315948893983"
  api_secret: "JebztEDFRwAEZt0RCE91fxzae20"
  
development:
  cloud_name: "kerjadulu-staging"
  api_key: "851315948893983"
  api_secret: "JebztEDFRwAEZt0RCE91fxzae20"

test:
  cloud_name: "kerjadulu-staging"
  api_key: "851315948893983"
  api_secret: "JebztEDFRwAEZt0RCE91fxzae20"
