# Key 亂放公開 Github 上會悲劇，確定這是 Trial Server

production:
  solr:
    hostname: 54.179.130.81
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
